### ISSUE TITLE
How to add contributors in my orgranization

### ISSUE THREAD

**Issue by mudongliang** [deepin-community/SIG#105]
Hi maintainers,

One contributor from our orgranization encountered some CLA issues[1]. I would like to add him to our organization. Is there any tutorial?

[1] https://github.com/linuxdeepin/deepin-system-upgrade/pull/21

**Comment by BLumia** [comment]
According to your profile bio, I assume you are in hust-cse group, if that's the case, head to https://github.com/deepin-community/SIG/blob/master/corporation/hust-cse/metadata.yml and submit a PR to add the contributor to the member list. Once the PR get merged, the CLA check shall pass.

**Comment by mudongliang** [comment]
Thanks, what's the meaning of field `id` in one contributor?

**Comment by BLumia** [comment]
You can get it from https://api.github.com/users/mudongliang, or you can also get it by accessing [your Profile page](https://github.com/mudongliang), then check the URL of your profile/avatar image, in this case it would be `https://avatars.githubusercontent.com/u/6214861?v=4`, then `6214861` is the `id` we want :)

**Comment by mudongliang** [comment]
I see. Thanks very much.

**Comment by mudongliang** [comment]
#106
