### ISSUE TITLE
新sig创建请求（抱歉，由于我最常用的平台并非github，且我不清楚一些事情，所以先开个issue）

### ISSUE THREAD

**Issue by Huayuluoshi** [deepin-community/SIG#424]
## 创建原因
当前，deepin和uos操作系统缺失音乐制作、视频剪辑、3D建模等等专业生产力软件，特此申请一个sig组进行适配（我本人是音乐制作爱好者）。
##sig组名称：深度创造（deepin-creativity）
## 仓库创建
此 SIG 需在 deepin-community 组织下创建如下仓库：
deepin-creativity-awesome 开源协议：CC-BY-SA-3.0
deepin-creativity-tools 开源协议：GPLv3【此仓库可能需要deepin官方repo支持，因为需要添加可下载内容】

***我的疑问：sig组必须2人以上吗？就我自己这样可以吗？谢谢！

**Comment by BLumia** [comment]
总体上还是欢迎的，不过下面还是先回答你的问题，以及一些关于你目前描述的提问讨论：

> 特此申请一个sig组进行适配

作为补充说明，开展对软件包的维护适配工作并不要求必须先建立 SIG 小组。加入现有小组或者单纯以个人身份进行维护也是可行的，当然如果满足小组创建条件的话我们还是很欢迎创建小组的 :)

> sig组必须2人以上吗？就我自己这样可以吗？

因为称为“组”，所以是约束的至少两人。我们强烈建议你通过 BBS、Matrix 聊天室等途径号召一下让至少另一位一同参与进来再建立这个 SIG。

当然，即便无法满足两个人的前提条件的话，你也是可以以个人身份发起贡献（包括参与维护软件包仓库）的，这点可以放心。

另外，无论是否能创建 deepin-creativity 小组，若你计划参与软件包的维护，我们还是强烈建议加入现有的 Matrix 群聊（尤其是 sysdev 小组），这样维护过程中的沟通会变得更方便。

> ...进行适配

我想问下，目前计划中，你的适配指的是具体怎样的适配呢？是指将主流开源的专业生产力软件打包进 deepin 官方软件包仓库吗？还是说移植到 linglong？或者说其它方式的适配支持？

> deepin-creativity-tools 开源协议：GPLv3【此仓库可能需要deepin官方repo支持，因为需要添加可下载内容】

这里的可下载内容指的是什么呢？

**Comment by Huayuluoshi** [comment]
好的，感谢。我明白你的建议了。下面是对一些疑问的回答：
1.Q：我想问下，目前计划中，你的适配指的是具体怎样的适配呢？
A：由于不确定性，我无法保证在别的发行版维护出来的软件在deepin中可用，所以需要在deepin中进行维护，称之为“适配”。“适配”的具体要求是指从源码或者二进制包进行维护，将主流或者实用的音频、视频等的独立的工作站软件及其可下载内容（下一个问题有说明）进行维护，以linglong包的形式或deb包的形式[计划是全部为玲珑格式，但视情况而定]进行打包并投递到deepin应用商店中，供用户下载。【此条需要应用商店开放生产力软件专区】
2.Q：这里的可下载内容指的是什么呢？
A：各类依赖于独立工作站的插件。众所周知，音频行业中离不开各种可被独立工作站识别、调用的插件（vst、vst3、lv2等等），视频行业中可能也有此类需求，这个可下载内容指的就是这种内容。此类内容只以文件存在，并非可执行文件，只能在工作站软件内被识别，故只需要工作站软件对某一目录有读取权限并且对应目录在deepin-creativity-tools软件中具有可写权限即可。目录位置可变动，不要求对根目录有写入权限。**这些可下载内容一般占用存储空间不大，但也有一些例外；不过占用较大的一般为闭源商业软件，deepin-creativity-tools软件包中不计划对其提供分发。

**Comment by BLumia** [comment]
> 计划是全部为玲珑格式，但视情况而定

如果计划如此的话，建议考虑加玲珑相关的适配群。因为 deepin 仓库打包和玲珑打包的整体处理方式还是不一样的，即便同样对生产力软件的移植感兴趣，也仍然需要对玲珑有一定了解才能有所帮助。

> 需要应用商店开放生产力软件专区

这个需要联系应用商店一侧来协调。目前商店的专区或者同性质的东西是商店从后端控制的，而非从我们的开源仓库一侧控制的。

> 众所周知，音频行业中离不开各种可被独立工作站识别、调用的插件（vst、vst3、lv2等等），视频行业中可能也有此类需求，这个可下载内容指的就是这种内容。

是否存在潜在的分发问题？或者说你仅打算移植开源或明确允许再分发的应用与插件吗？

举例而言，现在任何**新的**用户或开发者都无法再获取到 VST2 插件的再分发许可，这就意味着你即便理论上可以自己构建、移植得到 VST2 插件，但也无法合规的进行再分发。

（ps. 有兴趣加 deepin 开发者群讨论吗？如 https://t.me/deepin_community 或者 https://matrix.to/#/#deepin-community:deepin.org ，兴许还可以在那里得到一些感兴趣的人来组件 SIG）

**Comment by Huayuluoshi** [comment]
1.建议考虑加玲珑相关的适配群
这方面我已经加了移植玲珑的微信群了。
2.这个需要联系应用商店一侧
这个确实，不过问题不大，因为我可以直接在 deepin-creativity-tools软件包内附上deepin app store的链接来解决这个问题（刚刚想到的方案）
3.是否存在潜在的分发问题？
我认为不存在。vst2不允许再分发，但是那只是vst2 sdk，而这些插件本身不属于vst2 sdk，只是在构建二进制文件时用到了，在使用这些构建好的二进制插件中本身不存在vst*的相关内容。举个例子，构建chromium内核的应用软件时只是在build过程中需要相应依赖，build结束后的二进制包是不需要相关依赖项的。说白话就是，斯坦伯格的vst只是一个扳手，这个扳手是决定不了最后弄好的东西能不能自由分发。
详细地说，拿lsp plugins举例，实际上生成vst插件时靠的是lsp plugins的源代码，而非vst项目的源代码。
3.deepin开发者讨论群
我确实有兴趣加入，但是matrix协议的deepin服务器地址我找了一中午没找到……请问能指个路吗？谢谢!

**Comment by BLumia** [comment]
> 因为我可以直接在 deepin-creativity-tools软件包内附上deepin app store的链接来解决这个问题（刚刚想到的方案）

这是否意味着它不再需要是个（deepin 仓库内的，deb 格式的）软件包？

> 那只是vst2 sdk，而这些插件本身不属于vst2 sdk，只是在构建二进制文件时用到了，在使用这些构建好的二进制插件中本身不存在vst*的相关内容。

换句话说，你已经通过合规的渠道获取过 vst2 sdk 了吗？如果答案是否定的，那么你也无法得到合规的构建好的 vst2 插件二进制文件才对。

> 斯坦伯格的vst只是一个扳手，这个扳手是决定不了最后弄好的东西能不能自由分发。

但这并不是一个可以合规获得的扳手，无法合规取得 vst2 sdk 意味着你无法合规的构建得到 vst2 插件。这事实上也是 Steinberg 的本意。

> 我确实有兴趣加入，但是matrix协议的deepin服务器地址我找了一中午没找到……请问能指个路吗？谢谢!

上面其实贴了链接，这里再链接一次吧 :)

- deepin 中文语言开发者群： https://matrix.to/#/#deepin-community:deepin.org 或者 https://t.me/deepin_community （这两个平台有桥接，任选其一即可，尽管我们推荐使用 Matrix）。
- 玲珑群： https://matrix.to/#/#linglong:matrix.org

Matrix 相关介绍可参见 https://wiki.deepin.org/Matrix 。你可以使用任意主流 Matrix 平台（例如 Element 或者 Mozilla 的实例等）的账号加入对应的房间，不要求必须使用 deepin 的账号。

**Comment by Huayuluoshi** [comment]
1.这是否意味着它不再需要是个（deepin 仓库内的，deb 格式的）软件包？
看情况。我目前还没有研究玲珑包的音频处理特性和可行性，如果玲珑达不到要求，我会使用deb格式。但是我目前没有任何存储服务器，分发内容的存储可能是个问题。
2.换句话说，你已经通过合规的渠道获取过 vst2 sdk 了吗
正在争取。


***感谢你的帮助，我已经加入了deepin的matrix。

**Comment by Huayuluoshi** [comment]
或者，换个角度，其实大部分vst3等的开源插件、工作站的作者已经提供了二进制包，把这些收集起来供下载安装也可以。
关于sig的问题，我感觉可以放入星火应用商店的sig组？

**Comment by BLumia** [comment]
> 或者，换个角度，其实大部分vst3等的开源插件、工作站的作者已经提供了二进制包，把这些收集起来供下载安装也可以。

vst3 本身走 GPL 就没有任何问题的，如果是非开源的插件项目，只有预先提供的二进制包的话，只要原作者允许你再分发就可以。

但注意，深度发行版软件仓库（不是指指玲珑）是不允许这类包的，这种包可能可以进应用商店（应用商店仓库和 deepin 发行版软件包仓库是不同的）。

> 关于sig的问题，我感觉可以放入星火应用商店的sig组？

如果你找得到和你有意向一起组件 SIG 的人的话，你还是可以创建 deepin-creativity 小组的。如果无法满足人数要求的话，可以先以个人贡献者身份开展相关移植工作的 :)

**Comment by Huayuluoshi** [comment]
1.如果是非开源的插件项目
这个其实我考虑到了，我打算在软件内引导用户自行下载。在专业版上的签名问题我会自己想办法。
我理解deepin不收录未明确授权的非开源应用的行为，对于需要版权方授权分发的非开源软件，我不会将其放在deepin源内分发。
2.无法满足人数要求的话
这个其实说起来也不是非新sig不可，瞄了一眼发现星火的sig感觉也能用。但是毕竟星火并不专注于生产力软件，所以一时想着新建个sig来着。看情况吧！如果真的人数够了那就申请个新sig，不够的话就个人开发者或者在星火sig。
3.关于vst的使用许可问题
这个我已经向版权方申请了专有vst3使用许可了，大约7个工作日可以得到回复。届时我可以在不违反使用许可的情况下进行维护。

**Comment by Huayuluoshi** [comment]
鉴于我已了解相关内容，现关闭此issue。
